POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "other user blog",
  "author": "User 2 name",
  "url": "fakeurl.com",
  "likes": 1,
  "userId": "62c76521658f9635219acc02" 
}